---
abstract: 'A vaguely Rake/Make/Cake-like thing for Perl - create steps and let a planner run them'
author:
  - 'Dave Rolsky <drolsky@maxmind.com>'
build_requires:
  File::Temp: '0'
  Log::Dispatch::Array: '0'
  Path::Class: '0'
  Test::Differences: '0'
  Test::Fatal: '0'
  Test::More: '0'
  lib: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Stepford
requires:
  Carp: '0'
  Forest::Tree: '0'
  List::AllUtils: '0'
  Log::Dispatch: '0'
  Log::Dispatch::Null: '0'
  Module::Pluggable::Object: '0'
  Module::Runtime: '0'
  Moose: '0'
  Moose::Role: '0'
  MooseX::Params::Validate: '0'
  MooseX::StrictConstructor: '0'
  MooseX::Types: '0'
  MooseX::Types::Combine: '0'
  MooseX::Types::Common::Numeric: '0'
  MooseX::Types::Common::String: '0'
  MooseX::Types::Moose: '0'
  MooseX::Types::Path::Class: '0'
  Parallel::ForkManager: '0'
  Scalar::Util: '0'
  Throwable::Error: '0'
  Time::HiRes: '1.9726'
  namespace::autoclean: '0'
  parent: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/maxmind/Stepford/issues
  repository: git://github.com/maxmind/Stepford.git
version: '0.002003'
x_authority: cpan:DROLSKY
x_contributors:
  - 'Dave Rolsky <autarch@urth.org>'
  - 'Gregory Oschwald <goschwald@maxmind.com>'
  - 'Gregory Oschwald <oschwald@gmail.com>'
  - 'Olaf Alders <olaf@wundersolutions.com>'
